skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
trusttrail = "BtgvVKaXQMJsRUdZ8ahuBftnwDpYtass15TqTwsJJA9s"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
